version: '3.8'

services:
  # SQL Server database service
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Riwi2025**"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - student-network

  # Student Management API service
  studentservice:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "8080:80"
    # Map host port 8080 to container port 80
    depends_on:
      - sqlserver
    networks:
      - student-network
    restart: unless-stopped

networks:
  student-network:
    driver: bridge

volumes:
  sql-data:
